import type { Metadata } from "next";
import { Langar, Lato } from "next/font/google";
import "./globals.css";

const langar = Langar({ subsets: ['latin'], weight: '400' });
const lato = Lato({ subsets: ['latin'], weight: ['400','700'] });

export const metadata: Metadata = {
  title: "Porfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${lato.className} bg-background text-primary`}
      >
        {children}
      </body>
    </html>
  );
}
